GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/2
###
DELETE http://localhost:3001/api/notes/3
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "nguyen dz", 
    "important": false
}